create table imobiliaria (id int8 generated by default as identity, imobiliaria_email varchar(255) not null, is_admin boolean not null, imobiliaria_nome varchar(255) not null, imobiliaria_password varchar(255) not null, url_sistema varchar(255) not null, primary key (id));
create table negocio (dtype varchar(31) not null, id int8 generated by default as identity, fonte varchar(255), status varchar(255), cod_imovel varchar(255), date_in timestamp, date_out timestamp, id_bitrix int8, tipo varchar(255), imobiliaria_id int8 not null, pipeline_id int8 not null, responsavel_id int8, primary key (id));
create table pipeline (id int8 generated by default as identity, id_sistema int8 not null, tipo varchar(255), imobiliaria_id int8, primary key (id));
create table responsavel_negocio (id int8 generated by default as identity, email varchar(255), id_sistema int8 not null, name varchar(255), primary key (id));
alter table if exists negocio add constraint FKemgqne7n5v8tpeunphpiaw18v foreign key (imobiliaria_id) references imobiliaria;
alter table if exists negocio add constraint FK24u36d5mnhnio1mo0hpbm2m3g foreign key (pipeline_id) references pipeline;
alter table if exists negocio add constraint FKtmad80ojb3bgsv0wi5s32b1ql foreign key (responsavel_id) references responsavel_negocio;
alter table if exists pipeline add constraint FKfaj2graxlmit9wjs4palkdl6v foreign key (imobiliaria_id) references imobiliaria;
